development:
  interval: 5
  lot_size: 2
  profit: 0.1
  pair: COSS_ETH
  trade_limit: 0.01
  public_key: Public
  private_key: Private
  bot_personalization: 'YES'
  bot_strategy: 'BULL'
test:
  interval: 5
  lot_size: 30
  profit: 0.1
  pair: COSS_ETH
  trade_limit: 0.01
  public_key: Public
  private_key: Private
  bot_personalization: 'YES'
  bot_strategy: 'BULL'
production:
  interval: <%= ENV['INTERVAL'] %>
  lot_size: <%= ENV['LOT_SIZE'] %>
  profit: <%= ENV['PROFIT'] %>
  pair: <%= ENV['PAIR'] %>
  trade_limit: <%= ENV['TRADE_LIMIT'] %>
  public_key: <%= ENV['PUBLIC_KEY'] %>
  private_key: <%= ENV['PRIVATE_KEY'] %>
  bot_personalization: <%= ENV['BOT_PERSONALIZATION'].to_s.upcase == 'YES' %>
  bot_strategy: <%= ENV['BOT_STRATEGY'] %>